// Code generated by Slice Machine. DO NOT EDIT.

import ImageOnlyBlock from './ImageOnlyBlock';
import ImageTextSplitBlock from './ImageTextSplitBlock';
import MyServices from './MyServices';
import TextImageSplitBlock from './TextImageSplitBlock';
import TextOnlyBlock from './TextOnlyBlock';

export {
	ImageOnlyBlock,
	ImageTextSplitBlock,
	MyServices,
	TextImageSplitBlock,
	TextOnlyBlock,
};

export const components = {
	image_only_block: ImageOnlyBlock,
	image_text_split_block: ImageTextSplitBlock,
	my_services: MyServices,
	text_image_split_block: TextImageSplitBlock,
	text_only_block: TextOnlyBlock,
};
