// Code generated by Slice Machine. DO NOT EDIT.

import ImageTextSplitBlock from './ImageTextSplitBlock';
import TextImageSplitBlock from './TextImageSplitBlock';
import TextOnlyBlock from './TextOnlyBlock';

export {
	ImageTextSplitBlock,
	TextImageSplitBlock,
	TextOnlyBlock,
};

export const components = {
	image_text_split_block: ImageTextSplitBlock,
	text_image_split_block: TextImageSplitBlock,
	text_only_block: TextOnlyBlock,
};
