// Code generated by Slice Machine. DO NOT EDIT.

import TextImageSplitBlock from './TextImageSplitBlock';
import TextOnlyBlock from './TextOnlyBlock';

export {
	TextImageSplitBlock,
	TextOnlyBlock,
};

export const components = {
	text_image_split_block: TextImageSplitBlock,
	text_only_block: TextOnlyBlock,
};
